### ISSUE TITLE
ProcessOutput.Readlines blocks forever

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/os-lib#32]
In this simple example with Ammonite, `ProcessOutput.Readlines()` blocks forever whereas `stdout=Inherit` works ok.

Is this a bug?
```
> amm
Loading...
Welcome to the Ammonite Repl 2.0.4 (Scala 2.13.1 Java 11.0.6)
@ import os._ 
import os._

@ proc("cat","/etc/hosts").call(stdout=ProcessOu 
                             os.ProcessOutput             os.ProcessOutput$ReadBytes   os.ProcessOutput$Readlines  <--- it locked forever.
@ proc("cat","/etc/hosts").call(stdout=ProcessOutput.Readlines{l => println("####"+l)}) 
^CException in thread "cat /etc/hosts stdout thread" java.lang.NoClassDefFoundError: Could not initialize class ammonite.$sess.cmd1$
	at os.ProcessOutput$Readlines$$anon$3.run(SubProcess.scala:229)
	at java.base/java.lang.Thread.run(Thread.java:834)

Interrupted! (`repl.lastException.printStackTrace` for details)

@ proc("cat","/etc/hosts").call(stdout=Inherit) 
127.0.0.1	localhost myhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
```

**Comment by Flowdalic** [comment]
FWIW, this is only reproducible under Ammonite. Unlike `spawn()`, `call()` will wait for the child process to terminate. This does not appear to ever happen when this is run under Ammonite, hence it blocks forever. A thread dump show the following

1. The main thread waiting for the child process to terminate
```
"main" #1 prio=5 os_prio=0 cpu=1363.05ms elapsed=393.70s tid=0x00007f0104027000 nid=0x72149 in Object.wait()  [0x00007f010bdfb000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(java.base@11.0.17/Native Method)
    - waiting on <0x000000062bcf6038> (a java.lang.Thread)
    at java.lang.Thread.join(java.base@11.0.17/Thread.java:1300)
    - waiting to re-lock in wait() <0x000000062bcf6038> (a java.lang.Thread)
    at java.lang.Thread.join(java.base@11.0.17/Thread.java:1375)
    at os.SubProcess.$anonfun$join$1(SubProcess.scala:73)
    at os.SubProcess.$anonfun$join$1$adapted(SubProcess.scala:73)
    at os.SubProcess$$Lambda$1422/0x0000000800834040.apply(Unknown Source)
    at scala.Option.foreach(Option.scala:437)
    at os.SubProcess.join(SubProcess.scala:73)
    at os.proc.call(ProcessOps.scala:80)
    at ammonite.$sess.cmd1$.<clinit>(cmd1.sc:1)
    at ammonite.$sess.cmd1.$main(cmd1.sc)
```

2. The thread that monitors the child process being RUNNABLE but somehow also in `Object.wait()`. I am not yet sure how to interpret this:
```

"cat /etc/hosts stdout thread" #42 prio=5 os_prio=0 cpu=0.17ms elapsed=378.18s tid=0x00007f010511c800 nid=0x721c3 in Object.wait()  [0x00007f009e3ec000]
   java.lang.Thread.State: RUNNABLE
    at ammonite.$sess.cmd1$$$Lambda$1407/0x0000000800827040.apply(Unknown Source)
    at os.ProcessOutput$Readlines$$anon$3.run(SubProcess.scala:229)
    at java.lang.Thread.run(java.base@11.0.17/Thread.java:829)
```

In any case, this issue should probably be migrated from os-lib to Ammonite.

**Comment by Flowdalic** [comment]
It's probably the lock on `Interpreter` which the main thread aquires a few frame up in the stack
```
    at ammonite.util.Catching.flatMap(Res.scala:115)
    at ammonite.interp.Interpreter.evaluateLine(Interpreter.scala:289)
    - locked <0x00000006106735a8> (a ammonite.interp.Interpreter)
    at ammonite.interp.Interpreter.$anonfun$processLine$6(Interpreter.scala:277)
    at ammonite.interp.Interpreter$$Lambda$710/0x00000008005b4040.apply(Unknown Source)
    at ammonite.util.Res$Success.flatMap(Res.scala:62)
    at ammonite.interp.Interpreter.$anonfun$processLine$4(Interpreter.scala:260)
    at ammonite.interp.Interpreter$$Lambda$394/0x0000000800304040.apply(Unknown Source)
    at ammonite.util.Res$Success.flatMap(Res.scala:62)
    at ammonite.interp.Interpreter.$anonfun$processLine$2(Interpreter.scala:253)
    at ammonite.interp.Interpreter$$Lambda$385/0x00000008002fd840.apply(Unknown Source)
    at ammonite.util.Catching.flatMap(Res.scala:115)
    at ammonite.interp.Interpreter.processLine(Interpreter.scala:252)
    - locked <0x00000006106735a8> (a ammonite.interp.Interpreter)
    at ammonite.repl.Repl.$anonfun$action$8(Repl.scala:199)
    at ammonite.repl.Repl$$Lambda$1338/0x00000008007f3840.apply(Unknown Source)
    at ammonite.util.Res$Success.flatMap(Res.scala:62)
    at ammonite.repl.Repl.$anonfun$action$4(Repl.scala:186)
    at ammonite.repl.Repl$$Lambda$207/0x0000000800270840.apply(Unknown Source)
```
